# -*- coding: utf-8 -*-
"""testandoPython

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/135YMyN74Xz7zycWuW2XiVuW5ms5QUp2O
"""

pip install pytest

import pytest

!pytest test_calculadora.py